### ISSUE TITLE
Sass::SyntaxError at / Undefined mixin 'panel'.

### ISSUE THREAD

**Issue by matt-burgess** [RailsApps/rails-devise#12]
Following the install for Foundation5 I'm getting this error.

**Comment by DanielKehoe** [comment]
See https://github.com/RailsApps/learn-rails/issues/79

Make sure to specify Foundation 5 in the Gemfile:
```
gem 'foundation-rails', '~> 5.5'
```
The "squiggle" operator means use “pessimistic” versioning. It means use any version greater than 5.5 and less than 6.0.

After changing the Gemfile, be sure to run:
```
$ bundle update
```
to use the older foundation-rails gem.

**Comment by matt-burgess** [comment]
Thanks.  That did it!
