### ISSUE TITLE
Devise initializer issue

### ISSUE THREAD

**Issue by lucasmazza** [RailsApps/rails-devise#17]
Since to https://github.com/RailsApps/rails-devise/commit/d395efd728e5512cbf64a1a020b8669731716445, both `DeviseController` and `ApplicationController` (its parent controller) are loaded inside an initializer, before the app has been completely loaded and in scenarios where loading the app isn't necessary (like during `rake db:setup` or `rake routes` tasks).

This isn't recommended and it can cause different loading order bugs that are hard for developers to track down. As current Devise maintainer, I recommend moving the `configure_permitted_parameters` callback back to the `ApplicationController` class.

Related Devise issue - plataformatec/devise#3757

**Comment by vanitu** [comment]
+1

**Comment by vanitu** [comment]
solve issue as
changing in config/initializers/devise_permitted_parameters.rb

**from**

def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
 end

**to**

def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys: [:name])
    devise_parameter_sanitizer.permit(:account_update,keys: [:name])
  end

**Comment by Skaelv** [comment]
https://github.com/RailsApps/rails-devise/pull/18

**Comment by zachkrasner** [comment]
Thank you Vanitu!

**Comment by DanielKehoe** [comment]
Sorry it took a bit of time to address this issue because of other responsibilities.
